version: '2.2'

networks:
    net:

volumes:
    mysql:
    caddy:
        external: true

services:
    caddy:
        build: ./docker/caddy/
        command: caddy -agree -log stderr -ca "${CA_URL}" -email "${CA_EMAIL}"
        restart: always
        environment:
            - "CADDY_UUID_FILE=/root/.caddy/uuid-${DOMAIN}"
            - DOMAIN
            - HTTP_PORT
            - HTTPS_PORT
            - LEGACY_SOCKET_PORT
            - TLS_TYPE
            - CLOUDFLARE_EMAIL
            - CLOUDFLARE_API_KEY
        volumes:
            - caddy:/root/.caddy
            - ${EXISTING_CERT_DIR}:/existing-certs:ro
            - ./web:/var/www/html/web:ro
            - ./berrymotes/css:/var/www/html/web/berrymotes/css:ro
            - ./berrymotes/data:/var/www/html/web/berrymotes/data:ro
            - ./berrymotes/images:/var/www/html/web/berrymotes/images:ro
            - ./berrymotes/js:/var/www/html/web/berrymotes/js:ro
            - ./berrymotes/single_emotes:/var/www/html/web/berrymotes/single_emotes:ro
            - ${EXTRA_DIR}:/var/www/html/extra:ro
        ports:
            - '${HTTP_PORT}:${HTTP_PORT}/tcp'
            - '${HTTPS_PORT}:${HTTPS_PORT}/tcp'
            - '${LEGACY_SOCKET_PORT}:${LEGACY_SOCKET_PORT}/tcp'
        networks:
            - net
        depends_on:
            php:
                condition: service_healthy
            extra-php:
                condition: service_healthy

    php:
        build: ./docker/php/
        restart: always
        init: true
        environment:
            - DOMAIN
            - HTTPS_PORT
            - NO_CDN
            - MYSQL_PASSWORD
        volumes:
            - ./web:/var/www/html/web:ro
            - ./berrymotes/css:/var/www/html/web/berrymotes/css:ro
            - ./berrymotes/data:/var/www/html/web/berrymotes/data:ro
            - ./berrymotes/images:/var/www/html/web/berrymotes/images:ro
            - ./berrymotes/js:/var/www/html/web/berrymotes/js:ro
            - ./berrymotes/single_emotes:/var/www/html/web/berrymotes/single_emotes:ro
        expose:
            - '9000'
        networks:
            - net
        depends_on:
            mysql:
                condition: service_healthy

    extra-php:
        build: ./docker/php/
        restart: always
        init: true
        environment:
            - DOMAIN
            - HTTPS_PORT
        volumes:
            - ${EXTRA_DIR}:/var/www/html/extra
        expose:
            - '9000'
        networks:
            - net

    node:
        build: ./docker/node/
        restart: always
        init: true
        environment:
            - MYSQL_PASSWORD
        expose:
            - '8344'
        networks:
            - net
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        build: ./docker/mysql/
        command: --default-authentication-plugin=mysql_native_password --skip-performance-schema
        restart: always
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_ONETIME_PASSWORD=yes
            - MYSQL_DATABASE=berrytube
            - MYSQL_USER=berrytube
            - MYSQL_PASSWORD
        volumes:
            - mysql:/var/lib/mysql
        expose:
            - '3306'
        networks:
            - net
