version: '2'

networks:
    bt-net:

volumes:
    bt-caddy:

services:
    bt-caddy:
        build: ./docker/caddy/
        image: registry.gitlab.com/berrytube/berrytube/caddy:latest
        restart: always
        environment:
            - CLOUDFLARE_EMAIL
            - CLOUDFLARE_API_KEY
        volumes:
            - bt-caddy:/root/.caddy
            - ./web:/var/www/html:ro
        ports:
            - '80:80/tcp'
            - '443:443/tcp'
            - '8443:8443/tcp'
        networks:
            - bt-net

    bt-php:
        build: ./docker/php/
        image: registry.gitlab.com/berrytube/berrytube/php:latest
        restart: always
        volumes:
            - ./web:/var/www/html:ro
        expose:
            - '9000'
        networks:
            - bt-net

    bt-node:
        build: ./docker/node/
        image: registry.gitlab.com/berrytube/berrytube/node:latest
        command: node server.js
        restart: always
        expose:
            - '8443'
        networks:
            - bt-net

    bt-mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: berrytube
            MYSQL_USER: berrytube
            MYSQL_PASSWORD: berrytube
        volumes:
            - ./schema.sql:/docker-entrypoint-initdb.d/berrytube.sql:ro
            - ./database/:/var/lib/mysql
        expose:
            - '3306'
        networks:
            - bt-net
