version: '2.2'

volumes:
    mysql:
    selfsigned:

services:
    nginx:
        build: ./docker/nginx/
        restart: unless-stopped
        read_only: true
        environment:
            - DOMAIN
            - HTTP_PORT
            - HTTPS_PORT
            - LEGACY_SOCKET_PORT
            - TLS_TYPE
        volumes:
            - ./docker/nginx/config:/etc/nginx.source:ro
            - ./web:/var/www/html/web:ro
            - ./berrymotes/css:/var/www/html/web/berrymotes/css:ro
            - ./berrymotes/data:/var/www/html/web/berrymotes/data:ro
            - ./berrymotes/images:/var/www/html/web/berrymotes/images:ro
            - ./berrymotes/js:/var/www/html/web/berrymotes/js:ro
            - ./berrymotes/single_emotes:/var/www/html/web/berrymotes/single_emotes:ro
            - ${LETSENCRYPT_DIR}:/etc/letsencrypt:ro
            - ${EXTRA_DIR}:/var/www/html/extra:ro
            - selfsigned:/var/selfsigned
        tmpfs:
            - /etc/nginx
            - /var/cache/nginx
        ports:
            - '${HTTP_PORT}:${HTTP_PORT}/tcp'
            - '${HTTPS_PORT}:${HTTPS_PORT}/tcp'
            - '${LEGACY_SOCKET_PORT}:${LEGACY_SOCKET_PORT}/tcp'
        depends_on:
            php:
                condition: service_healthy
            extra-php:
                condition: service_healthy
        labels:
            tv.berrytube.cert-renew-signal: HUP

    php:
        build:
            context: ./docker/php/
            args:
                - MAXMIND_KEY
        restart: unless-stopped
        init: true
        environment:
            - DOMAIN
            - HTTPS_PORT
            - NO_CDN
            - NO_MINIFIED
            - MYSQL_PASSWORD
            - TLS_TYPE
        volumes:
            - ./web:/var/www/html/web:ro
            - ./berrymotes/css:/var/www/html/web/berrymotes/css:ro
            - ./berrymotes/data:/var/www/html/web/berrymotes/data:ro
            - ./berrymotes/images:/var/www/html/web/berrymotes/images:ro
            - ./berrymotes/js:/var/www/html/web/berrymotes/js:ro
            - ./berrymotes/single_emotes:/var/www/html/web/berrymotes/single_emotes:ro
        expose:
            - '9000'
        depends_on:
            mysql:
                condition: service_healthy

    extra-php:
        build: ./docker/php/
        restart: unless-stopped
        init: true
        environment:
            - DOMAIN
            - HTTPS_PORT
        volumes:
            - ${EXTRA_DIR}:/var/www/html/extra
        expose:
            - '9000'

    node:
        build: ./docker/node/
        restart: unless-stopped
        init: true
        environment:
            - MYSQL_PASSWORD
            - YOUTUBE_APIKEY
        expose:
            - '8344'
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        build: ./docker/mysql/
        command: --default-authentication-plugin=mysql_native_password --skip-performance-schema
        restart: unless-stopped
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_ONETIME_PASSWORD=yes
            - MYSQL_DATABASE=berrytube
            - MYSQL_USER=berrytube
            - MYSQL_PASSWORD
        volumes:
            - mysql:/var/lib/mysql
        expose:
            - '3306'
