version: '2'

volumes:
    database_data:
        driver: local

services:
    nginx:
        image: nginx:latest
        restart: always
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        expose:
            - 80
        links:
            - php
        ports:
            - "${WEB_PORT}:80"
    node:
        build: ./docker/node/
        image: registry.gitlab.com/berrytube/berrytube/node
        command: nodemon
        restart: always
        working_dir: /home/node/app
        volumes:
            - "./docker/node/:/home/node/app"
        expose:
            - 8344
        ports:
            - "${NODE_PORT}:8344"
        links:
            - mysql
        depends_on:
            - mysql
    php:
        build: ./docker/php/
        image: registry.gitlab.com/berrytube/berrytube/php
        restart: always
        expose:
            - 9000
        volumes:
            - .:/var/www/html
        links:
            - mysql
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
            - 3306
        volumes:
            - ./docker/db/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: local
