# In case of administrative emergencies
version: '2'
services:            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        expose: 
            - 80
        ports:
            - "8080:80"
        environment:
            PMA_USER: root
            PMA_PASSWORD: root
            PMA_HOST: mysql