version: '2'

volumes:
    database_data:
        driver: local

services:
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
    node:
        build: ./docker/node/
        restart: always
        working_dir: /home/node/app
        volumes:
            - "./docker/node/:/home/node/app"
        expose:
            - 8344
        ports:
            - "8344:8344"
        command: nodemon
    php:
        build: ./docker/php/
        restart: always
        expose:
            - 9000
        volumes:
            - .:/var/www/html 
        links:
            - mysql
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        restart: always
        expose:
            - 3306
        volumes:
            - ./docker/db/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: local