version: '2'

networks:
    net:

volumes:
    mysql:
    caddy:
        external: true

services:
    caddy:
        build: ./docker/caddy/
        command: caddy -agree -log stderr -ca "${CA_URL}" -email "${CA_EMAIL}"
        restart: always
        environment:
            - DOMAIN
            - CDN_DOMAIN
            - SOCKET_DOMAIN
            - HTTP_PORT
            - HTTPS_PORT
            - LEGACY_SOCKET_PORT
            - TLS_TYPE
            - CLOUDFLARE_EMAIL
            - CLOUDFLARE_API_KEY
        volumes:
            - caddy:/root/.caddy
            - ${EXISTING_CERT_DIR}:/existing-certs:ro
            - ./web:/var/www/html/web:ro
            - ./berrymotes/data:/var/www/html/berrymotes/data:ro
            - ./berrymotes/css:/var/www/html/berrymotes/css:ro
            - ./berrymotes/js:/var/www/html/berrymotes/js:ro
            - ./berrymotes/images:/var/www/html/berrymotes/images:ro
            - ./berrymotes/single_emotes:/var/www/html/berrymotes/single_emotes:ro
        ports:
            - '${HTTP_PORT}:${HTTP_PORT}/tcp'
            - '${HTTPS_PORT}:${HTTPS_PORT}/tcp'
            - '${LEGACY_SOCKET_PORT}:${LEGACY_SOCKET_PORT}/tcp'
        networks:
            - net
        depends_on:
            - php

    php:
        build: ./docker/php/
        restart: always
        environment:
            - DOMAIN
            - CDN_DOMAIN
            - SOCKET_DOMAIN
            - HTTP_PORT
            - HTTPS_PORT
            - LEGACY_SOCKET_PORT
            - NO_CDN
        volumes:
            - ./web:/var/www/html/web:ro
            - ./berrymotes/data:/var/www/html/berrymotes/data:ro
            - ./berrymotes/css:/var/www/html/berrymotes/css:ro
            - ./berrymotes/js:/var/www/html/berrymotes/js:ro
        expose:
            - '9000'
        networks:
            - net
        depends_on:
            - mysql

    node:
        build: ./docker/node/
        restart: always
        expose:
            - '8344'
        networks:
            - net
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: berrytube
            MYSQL_USER: berrytube
            MYSQL_PASSWORD: berrytube
        volumes:
            - mysql:/var/lib/mysql
            - ./schema.sql:/docker-entrypoint-initdb.d/berrytube.sql:ro
        expose:
            - '3306'
        networks:
            - net
