version: '2'

volumes:
    database_data:
        driver: local

services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
    node:
        build: ./docker/node/
        volumes:
            - "./docker/node/:/src"
        ports:
            - "8344:8344"
        command: nodemon
    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html 
        links:
            - mysql
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        hostname: mysql
        expose:
            - 3306
        ports:
            - "3306:3306"
        volumes:
            - ./docker/db/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: local
            MYSQL_USER: root
            MYSQL_PASSWORD: root