export const Errors = {
	PLAYER_UNKNOWN_ERROR: {code: 0, str: "PLAYER_UNKNOWN_ERROR"},
	PLAYER_INVALID_ID: {code: 1, str: "PLAYER_INVALID_ID"},
	PLAYER_UNPLAYABLE_VIDEO: {code: 2, str: "PLAYER_UNPLAYABLE_VIDEO"},
	PLAYER_GEOBLOCKED_VIDEO: {code: 3, str: "PLAYER_GEOBLOCKED_VIDEO"},
};
