location = /robots.txt {
    default_type text/plain;
    return 200 "User-Agent: *\nDisallow: /\n";
}

location = /.well-known/security.txt {
    default_type text/plain;
    return 200 "Contact: mailto:security@berrytube.tv\nPreferred-Languages: en\nExpires: 2030-01-01T00:00:00Z\n";
}

location ^~ /.well-known/ { }
location ~ /\. {
    return 404;
}
