import { StaticTable } from "lib/static-table";

// cSpell:disable

export const LogEvents = new StaticTable([
	{ id: "EVENT_PROC_UNHANDLED_EXCEPTION" },
	{ id: "EVENT_REPL" },
	{ id: "EVENT_SERVER_STATUS" },
]);

/*

To generate, run on the page in the comment:

JSON.stringify(
    Array.from(
        new Set(
            Array.from(document.querySelectorAll('#WikiaArticle table > tbody > tr > td:first-child > b'))
                .map(el => el.textContent)
                .filter(name => /^[A-Z]./.test(name))
        )
    ).sort()
)

*/

/*

To generate CSS class based list, run on BT:

JSON.stringify(
    Array.from(
        new Set(
            Array.from(document.querySelectorAll('*'))
                .flatMap(el => Array.from(el.classList))
        )
    )
    .filter(cl => !cl.startsWith('msg-') && !(cl in CHATLIST))
    .map(cl => cl.toLowerCase())
    .sort()
)

On the server can also do something like:

egrep -R --only-matching --no-filename '\.[a-zA-Z0-9]+' web/css/*.css berrymotes/css/*.css | sort | uniq | sed \
	's/^\.//' | tr '[A-Z]' '[a-z]' | jq -cRs '. / "\n"'

*/

export const Settings = {
	// Init Core settings
	Version: "3.0.0",
	nodeport: 8344, // the server listening port.
	log_file_name: "bt.log",
	error_file_name: "error_bt.log",
	debug_file_name: "debug.log",
	max_saved_buffer: 30, // # of saved messages in chatlog sent to people who join.
	db_commit_delay: 1000 * 60 * 10, // ms
	heartbeat_interval: 10000, // ms
	max_connections_per_ip: 100,
	auto_volatile: 600, // Seconds
	spamhp: 15000, // ms
	spamcompare: 3000, // ms
	max_chat_size: 400, // characters
	temp_ban_duration: 1000 * 60 * 60 * 12, // ms
	login_fail_duration: 1000 * 60 * 10, // ms
	max_failed_logins: 10, // Number of times an IP can password fail before getting locked out.
	register_cooldown: 1000 * 60 * 30, //ms
	country_restriction_ignored: ["DE", "IL"], // Some countries are particularly restrictive, ignore them.
	country_allow_required: ["GB", "CA", "US"], // Required countries if we have an allow list instead of a deny list
	bcrypt_rounds: 10,

	video_tail_time: 2, // seconds
	video_head_time: 3, // seconds

	// Init API keys
	api_youtube: process.env.YOUTUBE_APIKEY,

	database: {
		host: "mysql",
		post: 3306,
		mysql_user: "berrytube",
		mysql_pass: "berrytube",
		database: process.env.MYSQL_PASSWORD || "berrytube",
		video_table: "videos",
	},
};

export const NickBlacklist = new Set(
	[
		"act",
		"active",
		"admin",
		"anon",
		"berryemote",
		"berryemote-wrapper-inner",
		"berryemote-wrapper-outer",
		"berrymotes_button",
		"berrytweaks-dialog",
		"berrytweaks-flag",
		"berrytweaks-ircify-join",
		"berrytweaks-ircify-part",
		"berrytweaks-ircify-title",
		"berrytweaks-localtime",
		"berrytweaks-queue-playlist",
		"btn",
		"buttonlistcontainer",
		"cb",
		"chatbuffer",
		"chatlistname",
		"chevronbuttoncontainerdiv",
		"chevrondiv",
		"clear",
		"colortag",
		"controlbutton",
		"controlbuttondiv",
		"controlson",
		"countdown-no-notes",
		"countdown-note",
		"countdown-start-time",
		"countdown-time-diff",
		"countdown-title",
		"delete",
		"drinkshown",
		"dynarea",
		"editbtn",
		"elem",
		"end",
		"fa",
		"fa-4x",
		"fa-arrow-down",
		"fa-arrow-up",
		"fa-check-square-o",
		"fa-cogs",
		"fa-expand",
		"fa-glass",
		"fa-lg",
		"fa-list-alt",
		"fa-list-ul",
		"fa-magic",
		"fa-paint-brush",
		"fa-times",
		"fa-youtube-play",
		"first",
		"flair",
		"flair_0",
		"flair_5",
		"floatinner",
		"green",
		"groupbuttonwrapper",
		"hastoast",
		"header",
		"hidechatflair",
		"hoverzoomlink",
		"impele",
		"import",
		"layout_hd",
		"log",
		"loginas",
		"mainbtns",
		"me",
		"message",
		"misc",
		"msg",
		"mtclose",
		"nick",
		"note",
		"option",
		"optioncontainer",
		"options",
		"optionwrap",
		"overview",
		"playing",
		"plshown",
		"pollshown",
		"ponypen_btns",
		"preload",
		"previouslyenabled",
		"requeue",
		"resize",
		"scrollbar",
		"settings",
		"settingsbuttondiv",
		"settingspane",
		"settingstable",
		"showsbchatter",
		"showtimestamps",
		"slidebtn",
		"submit",
		"tab",
		"themebutton",
		"themebuttoncontainerdiv",
		"themebuttonwrapper",
		"thumb",
		"time",
		"timestamp",
		"title",
		"toastshown",
		"totallength",
		"totalvideos",
		"track",
		"transparent",
		"tweakbutt",
		"tweaked",
		"ui-helper-hidden-accessible",
		"ui-sortable",
		"ui-sortable-handle",
		"user",
		"vidshown",
		"viewport",
		"vjs-styles-defaults",
		"wrapper",
	]
		.concat([
			"0",
			"05em",
			"075",
			"08929em",
			"1",
			"12",
			"14",
			"165",
			"1em",
			"2",
			"3",
			"3em",
			"4",
			"4em",
			"5",
			"5em",
			"6",
			"7",
			"75",
			"7em",
			"8",
			"82",
			"95em",
			"act",
			"active",
			"ad",
			"admin",
			"anon",
			"assistant",
			"banzone",
			"bem",
			"berry",
			"berryemote",
			"berrymotes",
			"btn",
			"button",
			"ca",
			"cb",
			"center",
			"chatbuffer",
			"chatlistname",
			"clear",
			"close",
			"code",
			"colorgrid",
			"colortag",
			"confirm",
			"content",
			"controlson",
			"countdown",
			"createdat",
			"date",
			"dd",
			"delete",
			"dialogcontent",
			"dialogtitlebar",
			"dialogtoolbar",
			"dialogwindow",
			"disable",
			"disabled",
			"drink",
			"drinkflair",
			"drinkwrap",
			"elem",
			"end",
			"expanded",
			"fifty",
			"filtered",
			"flair",
			"flaunt",
			"flutter",
			"gif",
			"gilded",
			"graymute",
			"green",
			"half",
			"hidden",
			"hidechatflair",
			"highlight",
			"history",
			"ignored",
			"img",
			"impele",
			"import",
			"is",
			"jpg",
			"kicked",
			"kill",
			"leader",
			"level",
			"loading",
			"log",
			"loginas",
			"mainbtns",
			"me",
			"message",
			"misc",
			"mod",
			"msg",
			"multi",
			"name",
			"new",
			"newmsg",
			"nick",
			"nickwrap",
			"noads",
			"nobody",
			"note",
			"notify",
			"obscure",
			"optionlist",
			"options",
			"optionwrap",
			"overview",
			"pluginauthors",
			"plugindesc",
			"pluginenable",
			"pluginexists",
			"pluginnode",
			"plugintitle",
			"png",
			"poll",
			"pollnote",
			"ranked",
			"rcv",
			"reconnecting",
			"request",
			"requeue",
			"right",
			"rmtimer",
			"rotation",
			"row",
			"rulezone",
			"sbanned",
			"scrollabledialog",
			"scrollbar",
			"search",
			"searching",
			"server",
			"setnick",
			"settings",
			"setvolatile",
			"shitpost",
			"show",
			"showsbchatter",
			"showtimestamps",
			"slidebtn",
			"small",
			"spoiler",
			"squee",
			"submit",
			"swatch",
			"sweetiebot",
			"tab",
			"thumb",
			"time",
			"timestamp",
			"tiny",
			"title",
			"titlebar",
			"totallength",
			"totalvideos",
			"track",
			"tweaked",
			"unban",
			"viewport",
			"volatile",
			"voted",
			"warntext",
			"wide",
			"wrapper",
		])
		.concat(["admin", "mod", "moderator", "berrytube", "server"])
		.map(s => s.toLowerCase()),
);

NickBlacklist.delete("tab");

export const PonyNames = Array.from(
	new Set(
		// http://mlp.wikia.com/wiki/List_of_ponies/full
		[
			"Abra",
			"Ace Point",
			"Admiral Fairweather",
			"Admiral Fairy Flight",
			"Admiral Sherbert Burst",
			"Aloe",
			"Amethyst Maresbury",
			"Amethyst Star",
			"Angel Wings",
			"Annie Apple",
			"Apple Bloom",
			"Apple Brioche",
			"Apple Brown Betty",
			"Apple Bumpkin",
			"Apple Cider",
			"Apple Cinnamon",
			"Apple Cinnamon Crisp",
			"Apple Cobbler",
			"Apple Dumpling",
			"Apple Flora",
			"Apple Fritter",
			"Apple Honey",
			"Apple Leaves",
			"Apple Munchies",
			"Apple Rose",
			"Apple Split",
			"Apple Stars",
			"Apple Strudel",
			"Apple Tart",
			"Applejack",
			"Archer",
			"Aunt Orange",
			"Auntie Applesauce",
			"Aura",
			"Autumn Gem",
			"B. Sharp",
			"Babs Seed",
			"Bae Mare",
			"Bags Valet",
			"Baked Apples",
			"Banana Fluff",
			"Barber Groomsby",
			"BeauDe Mane",
			"Beauty Brass",
			"Berry Dreams",
			"Berry Preppy",
			"Berryshine",
			"Biff",
			"Big Bucks",
			"Big Daddy McColt",
			"Big McIntosh",
			"Big Shot",
			"Big Top",
			"Big Wig",
			"Bill Neigh",
			"Bittersweet",
			"Blaze",
			"Blossomforth",
			"Blue Bobbin",
			"Blue Buck",
			"Blue Moon",
			"Blueberry Curls",
			"Bluenote",
			"Bolt",
			"Bow Hothoof",
			"Bracer Britches",
			"Braeburn",
			"Bridle Buck",
			"Bright Bulb",
			"Bright Mac",
			"Bright Smile",
			"Buddy",
			"Bulk Biceps",
			"Bumpkin",
			"Buried Lede",
			"Burnt Oak",
			"Business Savvy",
			"Button Mash",
			"Calamity Mane",
			"Candy Apples",
			"Candy Caramel Tooth",
			"Caramel",
			"Caramel Apple",
			"Cattail",
			"Cerulean Skies",
			"Chancellor Neighsay",
			"Chancellor Puddinghead",
			"Charged Up",
			"Chargrill Breadwinner",
			"Charity Kindheart",
			"Cheerilee",
			"Cheese Sandwich",
			"Cherry Berry",
			"Cherry Fizzy",
			"Cherry Jubilee",
			"Cherry Spices",
			"Chipcutter",
			"Cinnamon Chai",
			"Cipher Splash",
			"Claude",
			"Clear Skies",
			"Cloud Chaser",
			"Cloud Kicker",
			"Cloudchaser",
			"Cloudy Quartz",
			"Clover the Clever",
			"Coco Pommel",
			"Coconut Cream",
			"Code Red",
			"Colonel Purple Dart",
			"Colonel Waffle",
			"Coloratura",
			"Comet Tail",
			"Commander Easyglider",
			"Commander Hurricane",
			"Commander Ironhead",
			"Compass Star",
			"Cookie Crumbles",
			"Coriander Cumin",
			"Cotton Cloudy",
			"Count Caesar",
			"Cozy Glow",
			"Crafty Crate",
			"Cratus",
			"Cream Puff",
			"Crusoe Palm",
			"Crystal Beau",
			"Crystal Hoof",
			"DJ Pon-3",
			"Daisy",
			"Dance Fever",
			"Dandy Grandeur",
			"Dane Tee Dove",
			"Daring Do",
			"Dark Moon",
			"Davenport",
			"Deputy Copper",
			"Derpy",
			"Diamond Cutter",
			"Diamond Mint",
			"Diamond Tiara",
			"Discord",
			"Doctor Horse",
			"Don Neigh",
			"Double Diamond",
			"Dr. Caballeron",
			"Dr. Fauna",
			"Dr. Hooves",
			"Dr. Horse",
			"Eclair Crème",
			"Eff Stop",
			"Elbow Grease",
			"Electric Sky",
			"Emerald Green",
			"Ernie",
			"Fancy Pants",
			"Fashion Plate",
			"Fast Clip",
			"Feather Bangs",
			"Featherweight",
			"Feldspar Granite Pie",
			"Felix",
			"Fiddly Twang",
			"Fili-Second",
			"Filthy Rich",
			"Fine Line",
			"Finish Line",
			"Fire Streak",
			"Firelight",
			"Flair d'Mare",
			"Flam",
			"Flash Magnus",
			"Flash Prance",
			"Flash Sentry",
			"Fleetfoot",
			"Fleur De Verre",
			"Fleur de Lis",
			"Flim",
			"Flitter",
			"Florina Tart",
			"Flourish Prose",
			"Fluffy Clouds",
			"Flurry Heart",
			"Flutterholly",
			"Fluttershy",
			"Foggy Fleece",
			"Four Step",
			"Frederick Horseshoepin",
			"Full Steam",
			"Gala Appleby",
			"General Blazing Donut Glaze",
			"General Firefly",
			"General Flash",
			"Ginger Beard",
			"Gizmo",
			"Gladmane",
			"Globe Trotter",
			"Golden Delicious",
			"Golden Gavel",
			"Golden Glitter",
			"Golden Harvest",
			"Golden Hooves",
			"Golden Wheat",
			"Goldengrape",
			"Goldie Delicious",
			"Grand Pear",
			"Granny Pie",
			"Granny Smith",
			"Grape Delight",
			"Green Jewel",
			"Grogar",
			"Grub Hooffield",
			"Gusty the Great",
			"Hairpin Turn",
			"Half Baked Apple",
			"Hard Hat",
			"Hayhoof",
			"Haymaker",
			"Hayscartes",
			"Hayseed Turnip Truck",
			"Headmaster Wing",
			"Helia",
			"High Spirits",
			"High Winds",
			"Hinny of the Hills",
			"Hock Fetlock",
			"Hoity Toity",
			"Holder Cobblestone",
			"Holly Dash",
			"Hondo Flanks",
			"Honey Rays",
			"Honeysparkle",
			"Hoofdini",
			"Hoofer Steps",
			"Hoops",
			"Hughbert Jellius",
			"Igneous Rock Pie",
			"Impossibly Rich",
			"Inky Rose",
			"Ivory Rook",
			"Jack Hammer",
			"Jack Pot",
			"Janine Manewitz",
			"Jeff Letrotski",
			"Jesús Pezuña",
			"Jet Set",
			"Jetstream",
			"Joan Pommelway",
			"Joe",
			"Jonagold",
			"June",
			"Junebug",
			"Juniper Montage",
			"Kettle Corn",
			"King Bullion",
			"King Sombra",
			"Lady Gaval",
			"Laurette",
			"Lavender Bloom",
			"Lavender Fritter",
			"Leadwing",
			"Lemon Hearts",
			"Lemony Gem",
			"Levon Song",
			"Lickety Split",
			"Lightning Dust",
			"Lightning Streak",
			"Lilac Hearts",
			"Lilac Links",
			"Lilac Luster",
			"Lilac Sky",
			"Lily Lace",
			"Lily Valley",
			"Limestone Pie",
			"Liza Doolots",
			"Long Shot",
			"Lotus Blossom",
			"Luckette",
			"Lucky Clover",
			"Lucky Star",
			"Lucy Packard",
			"Lyra Heartstrings",
			"Lyrica Lilac",
			"Ma Hooffield",
			"Madden",
			"Mage Meadowbrook",
			"Magnet Bolt",
			"Mane Moon",
			"Mane-iac",
			"Manely Gold",
			"Marble Pie",
			"Mare Do Well",
			"Mare E. Belle",
			"Mare E. Lynn",
			"Masked Matter-Horn",
			"Maud Pie",
			"Mayor Baltimare",
			"Mayor Cream Cheese",
			"Mayor Mare",
			"Meadow Flower",
			"Meadow Song",
			"Merry",
			"Merry May",
			"Midnight Fun",
			"Midnight Strike",
			"Minuette",
			"Mistmane",
			"Mistress Mare-velous",
			"Misty Fly",
			"Moon Dancer",
			"Mr. Breezy",
			"Mr. Carrot Cake",
			"Mr. Greenhooves",
			"Mr. Kingpin",
			"Mr. Paleo",
			"Mr. Pearblossom",
			"Mr. Shy",
			"Mr. Stripes",
			"Mr. Waddle",
			"Mrs. Cup Cake",
			"Mrs. Paleo",
			"Mrs. Pearblossom",
			"Mrs. Shy",
			"Mrs. Trotsworth",
			"Ms. Harshwhinny",
			"Ms. Peachbottom",
			"Mudbriar",
			"Namby-Pamby",
			"Nana Pinkie",
			"Neigh Sayer",
			"Neon Lights",
			"Night Glider",
			"Night Light",
			"Night Watch",
			"Nightjar",
			"Nimble Thimble",
			"Noteworthy",
			"Nurse Redheart",
			"Nurse Snowheart",
			"Octavia Melody",
			"Ol' Salt",
			"On Stage",
			"Open Skies",
			"Orange Slice",
			"Orange Swirl",
			"Pacific Glow",
			"Parasol",
			"Parcel Post",
			"Parish Nandermane",
			"Party Favor",
			"Peachy Pie",
			"Peachy Pitt",
			"Peachy Sweet",
			"Pear Butter",
			"Pearly Stitch",
			"Pegasus Olsen",
			"Perfect Pace",
			"Perfect Pie",
			"Periwinkle Pace",
			"Petunia Paleo",
			"Photo Finish",
			"Picture Frame",
			"Piles McColt",
			"Pine Apple",
			"Pinkie Pie",
			"Pinny Lane",
			"Pipsqueak",
			"Pizza Pie",
			"Pizzelle",
			"Plaid Stripes",
			"Pop Fly",
			"Pound Cake",
			"Powder Rouge",
			"Press Release",
			"Pretty Vision",
			"Pretzel",
			"Prim Hemline",
			"Prim Posy",
			"Prince Blueblood",
			"Prince Hisan",
			"Princess Amore",
			"Princess Cadance",
			"Princess Celestia",
			"Princess Luna",
			"Princess Platinum",
			"Prism Glider",
			"Private Pansy",
			"Professor Flintheart",
			"Professor Fossil",
			"Pumpkin Cake",
			"Purple Wave",
			"Pursey Pink",
			"Queen Cleopatrot",
			"Queso Fresca",
			"Quibble Pants",
			"Quilland Ink",
			"Radiance",
			"Rainbow Blaze",
			"Rainbow Dash",
			"Rainbow Swoop",
			"Rainbowshine",
			"Randolph",
			"Rapidfire",
			"Rare Find",
			"Rarity",
			"Raspberry Beret",
			"Raven Inkwell",
			"Red Delicious",
			"Red Gala",
			"Rockhoof",
			"Rococo Froufrou",
			"Roger Silvermane",
			"Rogue",
			"Rooks Rampart",
			"Rose",
			"Rough Tumble",
			"Roxie Rave",
			"Royal Pin",
			"Royal Ribbon",
			"Royal Riff",
			"Ruby Splash",
			"Rumble",
			"Rusty Tenure",
			"Sable Spirit",
			"Saddle Rager",
			"Saffron Masala",
			"Sand Trap",
			"Sandbar",
			"Sapphire Joy",
			"Sapphire Shores",
			"Sassaflash",
			"Sassy Saddles",
			"Savoir Fare",
			"Scootaloo",
			"Screwball",
			"Screwy",
			"Sea Swirl",
			"Sealed Scroll",
			"Shadow Spade",
			"Sheriff Silverstar",
			"Shining Armor",
			"Shoeshine",
			"Shooting Star",
			"Silver Berry",
			"Silver Frames",
			"Silver Shill",
			"Silver Spanner",
			"Silver Spoon",
			"Silver Zoom",
			"Silverspeed",
			"Skeedaddle",
			"Sky Stinger",
			"Smart Cookie",
			"Smash Fortune",
			"Snails",
			"Snappy Scoop",
			"Snips",
			"Snowdash",
			"Snowfall Frost",
			"Soarin",
			"Soigne Folio",
			"Somnambula",
			"Songbird Serenade",
			"Spearhead",
			"Spitfire",
			"Spoiled Rich",
			"Spring Forward",
			"Spring Step",
			"Sprinkle Medley",
			"Star Hunter",
			"Star Spur",
			"Star Swirl the Bearded",
			"Star Tracker",
			"Starburst",
			"Starlight Glimmer",
			"Starry Eyes",
			"Starstreak",
			"Steam Roller",
			"Stella Lashes",
			"Stellar Eclipse",
			"Stellar Flare",
			"Stinkin' Rich",
			"Stinky Bottom",
			"Stormbreaker",
			"Stormfeather",
			"Stormy Flare",
			"Strawberry Ice",
			"Strawberry Sunrise",
			"Strike",
			"Stygian",
			"Sugar Belle",
			"Sugar Twist",
			"Sunburst",
			"Sunflower",
			"Sunny Daze",
			"Sunny Rays",
			"Sunny Smiles",
			"Sunset Shimmer",
			"Sunshine Petals",
			"Sunshower",
			"Sunshower Raindrops",
			"Super Stream",
			"Suri Polomare",
			"Surprise",
			"Svengallop",
			"Swan Song",
			"Swanky Hank",
			"Sweetie Belle",
			"Sweetie Drops",
			"Symphony Song",
			"Tall Order",
			"Tall Tale",
			"Tempest Shadow",
			"Tender Taps",
			"The Great and Powerful Trixie",
			"The Headless Horse",
			"The Olden Pony",
			"Thornhoof",
			"Thunderlane",
			"Tight Ship",
			"Toe-Tapper",
			"Toola Roola",
			"Top Marks",
			"Torch Song",
			"Trapeze Star",
			"Tree Hugger",
			"Trenderhoof",
			"Tropical Storm",
			"Trotter",
			"Trouble Shoes",
			"Truffle",
			"Twilight Sky",
			"Twilight Sparkle",
			"Twilight Velvet",
			"Twinkleshine",
			"Twist",
			"Twisty Pop",
			"Uncle Orange",
			"Upper Crust",
			"Upper East Stride",
			"Vapor Trail",
			"Vidala Swoon",
			"Vinny",
			"Walter",
			"Warm Front",
			"Wave Chill",
			"Wensley",
			"Whinnyfield",
			"Whiplash",
			"White Lightning",
			"Whitewash",
			"Wild Bull Hickok",
			"Wild Fire",
			"Wind Rider",
			"Windy Whistles",
			"Withers",
			"Wolfgang Canter",
			"Wrangler",
			"Zapp",
			"Zephyr Breeze",
			"Zesty Gourmand",
			"Zipporwhill",
		].concat(
			// http://mlp.wikia.com/wiki/List_of_non-pony_characters
			[
				"Ace",
				"Adagio Dazzle",
				"Ahuizotl",
				"Albus",
				"Allie",
				"Amaryllis",
				"Angel",
				"Angus McSteer",
				"Apple Bloom",
				"Applejack",
				"Aria Blaze",
				"Arimaspi",
				"Arrow",
				"Avery",
				"Baast",
				"Bad Apple",
				"Bela",
				"Bernard Rabbit",
				"Bertha",
				"Bessie",
				"Big Angie",
				"Big Boy",
				"Big Jim",
				"Blackbeak",
				"Blackthorn",
				"Blacktip",
				"Bloomberg",
				"Blue-Blue",
				"Boneless",
				"Boris",
				"Boulder",
				"Boyle",
				"Bramble",
				"Braze",
				"Breezette",
				"Brendan",
				"Brian",
				"Bruce",
				"Brunella",
				"Bruno",
				"Brutus",
				"Brutus Force",
				"Bubble Splash",
				"Buffalo Bull",
				"Buffy",
				"Bunny",
				"Buttercream Sunday",
				"Calvin",
				"Calvin & Theo",
				"Capper",
				"Captain Blister",
				"Captain Celaeno",
				"Captain Rosella",
				"Cassie",
				"Castor",
				"Cerberus",
				"Charlie",
				"Chief Thunderhooves",
				"Chocolate Moose",
				"Chrysalis",
				"Chummer",
				"Cloudia Breezie",
				"Coach Klaus",
				"Cobalt Cloudhunter",
				"Constance",
				"Coral",
				"Coralita",
				"Cornicle",
				"Crackle",
				"Cranky Doodle Donkey",
				"Cranky Doodle Ryan",
				"Crystal Pearl",
				"Cyclops-clops",
				"DaisyJo",
				"Dea",
				"Delilah",
				"Denise",
				"Diamond Tiara",
				"Discord",
				"Doc Holstein",
				"Doran",
				"Edgar",
				"Electra",
				"Elizabeak",
				"Elke",
				"Elle on the Inside",
				"Ember",
				"Faye",
				"Fernando",
				"Fido",
				"Firebrand",
				"Firegem",
				"Flap",
				"Flash Feather",
				"Flip",
				"Fluffy",
				"Fluffy Bun",
				"Flutter Cloud",
				"Fluttershy",
				"Foo Foo",
				"Frankenstag's monster",
				"Franz",
				"Fume",
				"Fuzzy Legs",
				"Gabby",
				"Gaea Everfree",
				"Gaiman",
				"Gallus",
				"Garble",
				"Garnet Flash",
				"Gavin",
				"General Seaspray",
				"Gertie",
				"Gestal",
				"Gil",
				"Gilda",
				"Giselle",
				"Gladys",
				"Glenda",
				"Goldstone",
				"Good Apple",
				"Grampa Gruff",
				"Gregor",
				"Greta",
				"Gretchen",
				"Grubber",
				"Grumm",
				"Grumpy Cat",
				"Gummy",
				"Gustave le Grand",
				"Hannah",
				"Harry",
				"Haven Bay",
				"Henrita",
				"Hilda",
				"Holder's Boulder",
				"Horwitz",
				"Hubert",
				"Hummingway",
				"Iggy",
				"Imp",
				"Insidira",
				"Ira",
				"Iron Will",
				"Isabella",
				"Jamal",
				"Jelly Bee",
				"Jerome",
				"Jersey Shore",
				"Jewel",
				"Jim",
				"Judy",
				"Katherine",
				"Kevin",
				"King Anubis",
				"King Aspen",
				"King Grover",
				"King Guto",
				"King Leo",
				"King Longhorn",
				"King Vorak",
				"King of Abyssinia",
				"Knuckerbocker",
				"Larry",
				"Lemon Squeezy",
				"Leroy",
				"Lilac Breezie",
				"Lilly Drop",
				"Little Strongheart",
				"Lix Spittle",
				"Lola",
				"Lord Tirek",
				"Louise",
				"Madame le Flour",
				"Mallory Hagan",
				"Manny Roar",
				"Marco",
				"Maredenkainen’s Faithful Hound",
				"Marina",
				"Matilda",
				"Melvin",
				"Metty",
				"Mina",
				"Miss Buffy",
				"Miss Kitty",
				"Moo-riella",
				"Mori",
				"Mr. Beaverton Beaverteeth",
				"Mr. Gossamer",
				"Mr. Jackalope",
				"Mr. McBitey-Pants",
				"Mr. Mousey",
				"Mr. Robin",
				"Mr. Turnip",
				"Mulia Mild",
				"Mullet",
				"Nar Wally",
				"Needy",
				"Nutso",
				"Ocean Flow",
				"Ocean Gem",
				"Ocellus",
				"Opalescence",
				"Owlowiscious",
				"Patrick",
				"Pearl",
				"Peewee",
				"Pepper Clark",
				"Pharynx",
				"Philomena",
				"Phoebe Grizelda Howell",
				"Piggington",
				"Pink Bunny",
				"Pinkie Pie",
				"Pinwheel",
				"Pollux",
				"Prince Crompus",
				"Prince Dromius",
				"Prince Gruntwig",
				"Prince Rutherford",
				"Prince Ulysses",
				"Princess Skystar",
				"Puce Sharptooth",
				"Pushkin",
				"Putt-Putt",
				"Queen Chrysalis",
				"Queen Haydon",
				"Queen Novo",
				"Queen of Abyssinia",
				"Queen of the Hippos",
				"Quincy",
				"Rabia",
				"Rainbow Dash",
				"Ralph",
				"Random Breezie",
				"Rarity",
				"Reginald",
				"Rinehart",
				"Ripley",
				"Rockie",
				"Rocky",
				"Rover",
				"Runt",
				"Rupert",
				"Sable",
				"Salina Blue",
				"Sam",
				"Santa Claus",
				"Scalio",
				"Scaly Sue",
				"Scintilla",
				"Scootaloo",
				"Scorchy",
				"Scorpan",
				"Scout",
				"Sea Breezie",
				"Sea Foam",
				"Sea Poppy",
				"Seabreeze",
				"Seddy",
				"Sendak the Elder",
				"Senior Huevos",
				"Sergio",
				"Shelby",
				"Sheldon",
				"Shellanda",
				"Shellbert",
				"Shelly",
				"Shelton",
				"Silver Spoon",
				"Silverstream",
				"Sir Discord",
				"Sir Lintsalot",
				"Skellinore",
				"Sky Beak",
				"Smarty Pants",
				"Smartyhoof",
				"Smoky",
				"Smoky Jr.",
				"Smolder",
				"Sneezy",
				"Softpad",
				"Sonata Dusk",
				"Sophie",
				"Spike",
				"Spirit of Hearth's Warming Past",
				"Spirit of Hearth's Warming Presents",
				"Spirit of Hearth's Warming Yet to Come",
				"Spooky",
				"Sporedust Butterfly",
				"Spot",
				"Spryyg",
				"Squabble",
				"Squizard",
				"Steffan",
				"Steven Magnet",
				"Stratus Skyranger",
				"Strife",
				"Sun Twist",
				"Sunny Breezie",
				"Sunset Breezie",
				"Sweeps",
				"Sweetie Belle",
				"Tabitha",
				"Tank",
				"Terramar",
				"The Enlightenment Broker",
				"The Smooze",
				"The Storm King",
				"Thorax",
				"Tiberius",
				"Tina",
				"Toby",
				"Tom",
				"Torch",
				"Tori Spelling",
				"Twiggy",
				"Twilight Sparkle",
				"Twirly",
				"Unless",
				"Urtica",
				"Vera",
				"Verko",
				"Vermouth Roux",
				"Vetera",
				"Vex",
				"Webfather",
				"Well-to-Do",
				"Whiskers",
				"Wigford",
				"William Wormsworth",
				"Windfall",
				"Windy",
				"Winona",
				"Yakatar",
				"Yakmina",
				"Yeehaw",
				"Yigrid",
				"Yona",
				"Zecora",
			],
		),
	),
);
