var PONTS = [
	'Applejack',
	'Pinkie Pie',
	'Fluttershy',
	'Rainbow Dash',
	'Rarity',
	'Twilight Sparkle',
	'Apple Bloom',
	'Scootaloo',
	'Sweetie Belle',
	'Big McIntosh',
	'Braeburn',
	'Carrot Cake',
	'Cup Cake',
	'Cheerilee',
	'Granny Smith',
	'Hoity Toity',
	'Mayor Mare',
	'Photo Finish',
	'Sapphire Shores',
	'Daring Do',
	'Derpy',
	'Soarin',
	'Spitfire',
	'Cadance',
	'Celestia',
	'Luna',
	'Fancypants',
	'Flam',
	'Flim',
	'Doughnut Joe',
	'Blueblood',
	'Shining Armor',
	'Trixie',
	'Diamond Tiara',
	'Featherweight',
	'Pipsqueak',
	'Pound Cake',
	'Pumpkin Cake',
	'Silver Spoon',
	'Snails',
	'Snips',
	'TWIST',
	'Aunt Orange',
	'Uncle Orange',
	'Berry Punch',
	'Berry Punch',
	'Berry Punch',
	'Bon Bon',
	'Cherry Jubilee',
	'Daisy',
	'Lily',
	'Rose',
	'Carrot Top',
	'Hayseed Turnip Truck',
	'Jeff Letrotski',
	'Walter Coltchak',
	'Junebug',
	'Octavia',
	'Screw Loose',
	'Sheriff Silverstar',
	'Dr. Whooves',
	'Fleetfoot',
	'Blossomforth',
	'Cloudchaser',
	'Flitter',
	'Snowflake',
	'Thunderlane',
	'Vinyl Scratch',
	'Jet Set',
	'Lyra',
	'Rumble',
	'Star Swirl the Bearded',
	'Namby-Pamby',
	'Lotus',
	'Aloe',
	'Crackle',
	'Spike',
	'Pee-Wee',
	'Discord',
	'Gilda',
	'Zecora',
	'Little Strongheart',
	'Chief Thunderhooves',
	'Cranky Doodle Donkey',
	'Matilda',
	'Iron Will',
	'Bloomberg',
	'Tom',
	'Smarty Pants',
	'Ahuizotl',
	'Angel',
	'Winona',
	'Opalescence',
	'Gummy',
	'Philomena',
	'Owlowiscious',
	'Tank',
	'Cerberus',
	'Steven Magnet',
	'Chrysalis'
];

module.exports = PONTS;
