CREATE TABLE tokens (
    token VARCHAR(36) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    nick VARCHAR(16) NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (token),
    CONSTRAINT fk_user
    FOREIGN KEY (nick)
    REFERENCES users(name)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
